#!/usr/bin/env python3
"""PPT Master - Read-only Project Space Report

Report disk usage per project and per artifact type under a projects root.
**Never deletes, moves, or modifies anything.** The ``--archive-plan`` output
lists precise paths of renewable artifacts with their reclaimable size and a
regeneration note — a dry-run plan for the user to approve before any cleanup.

Renewability (Brief Phase 6.2): images / sources / spec+design locks / notes /
annotations / SVG pages / exports are NON-renewable (never suggested). Only
cached or derived artifacts (backup/, dashboard/, validation/, quality/,
.preview/, trace.jsonl) are classified renewable.

Usage:
    python3 scripts/space_report.py <projects_root>
    python3 scripts/space_report.py <projects_root> --archive-plan <out.json>
    python3 scripts/space_report.py <projects_root> --json-out <file> --top 5

Dependencies:
    None (stdlib only).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

REPORT_SCHEMA = "ppt-master.space-report.v1"
# Non-renewable artifact dirs/files — never suggested for archive/cleanup.
_NON_RENEWABLE = {
    "sources", "images", "exports", "notes", "svg_output", "svg_final",
    "analysis", "icons", "_research", "confirm_ui", "annotations",
}
_NON_RENEWABLE_FILES = {
    "spec_lock.md", "design_spec.md", "page_expression.json",
    "content_selection.json", "detailed_outline.json", "research_report.md",
    "research_analysis.json", "visual_strategy.json",
}
# Renewable (derived/cached) — candidates for a user-approved archive plan.
_RENEWABLE = {
    "backup", "dashboard", "validation", "quality", ".preview",
    ".codex", ".tmp", "__pycache__", ".preview2",
}


def _classify(rel: str) -> str:
    """renewable | non-renewable | other."""
    parts = [p for p in rel.replace("\\", "/").split("/") if p]
    top = parts[0] if parts else rel
    if top in _RENEWABLE or top.startswith(".") and top not in {".spec_lock.digest"}:
        return "renewable"
    if top in _NON_RENEWABLE:
        return "non-renewable"
    if parts and parts[-1] in _NON_RENEWABLE_FILES:
        return "non-renewable"
    if top in {"trace.jsonl"} or rel.endswith(".log"):
        return "renewable"
    return "other"


def _dir_size(path: Path) -> int:
    total = 0
    try:
        for f in path.rglob("*"):
            if f.is_file():
                try:
                    total += f.stat().st_size
                except OSError:
                    pass
    except OSError:
        pass
    return total


def _project_report(project: Path) -> dict[str, Any]:
    by_type: dict[str, dict[str, Any]] = {}
    total = 0
    renewable = 0
    for f in project.rglob("*"):
        if not f.is_file():
            continue
        try:
            size = f.stat().st_size
        except OSError:
            continue
        rel = f.relative_to(project).as_posix()
        kind = _classify(rel)
        bucket = by_type.setdefault(kind, {"count": 0, "bytes": 0})
        bucket["count"] += 1
        bucket["bytes"] += size
        total += size
        if kind == "renewable":
            renewable += size
    return {
        "project": project.name,
        "bytes": total,
        "renewable_bytes": renewable,
        "by_class": by_type,
    }


def _archive_plan(project: Path) -> list[dict[str, Any]]:
    """Precise renewable-artifact paths with size and regeneration note."""
    plan: list[dict[str, Any]] = []
    for f in project.rglob("*"):
        if not f.is_file():
            continue
        rel = f.relative_to(project).as_posix()
        if _classify(rel) != "renewable":
            continue
        try:
            size = f.stat().st_size
        except OSError:
            continue
        top = rel.split("/")[0]
        plan.append({
            "path": rel,
            "bytes": size,
            "class": top,
            "recovery": _recovery_note(top),
        })
    return plan


def _recovery_note(kind: str) -> str:
    notes = {
        "backup": "recreate from a fresh snapshot command; verify contents before deleting",
        "dashboard": "regenerated on next dashboard run",
        "validation": "regenerated by svg_quality_checker / e2e_validate / svg_to_pptx",
        "quality": "regenerated by harness_gate / pptx_quality_check / run_summary",
        ".preview": "regenerated by visual_review.py",
        ".codex": "agent scratch cache; safe to clear on demand",
        "__pycache__": "regenerated by Python import",
        "trace.jsonl": "regenerated on the next pipeline run (metrics history lost)",
    }
    return notes.get(kind, "derived artifact; see owning script doc for regeneration")


def build_report(projects_root: Path, top: int = 5) -> dict[str, Any]:
    projects = sorted(
        (p for p in projects_root.iterdir() if p.is_dir()),
        key=lambda p: -_dir_size(p),
    )
    reports = [_project_report(p) for p in projects]
    totals: dict[str, Any] = {"bytes": 0, "renewable_bytes": 0, "projects": len(reports)}
    for rep in reports:
        totals["bytes"] += rep["bytes"]
        totals["renewable_bytes"] += rep["renewable_bytes"]
    return {
        "schema": REPORT_SCHEMA,
        "projects_root": str(projects_root),
        "checked_at": datetime.now(timezone.utc).isoformat(),
        "summary": totals,
        "top_projects": [
            {
                "project": rep["project"],
                "bytes": rep["bytes"],
                "renewable_bytes": rep["renewable_bytes"],
            }
            for rep in reports[:top]
        ],
        "projects": reports,
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="space_report.py",
        description=(
            "只读项目空间报告：按项目/artifact 类型统计占用。绝不删除或移动任何文件。"
            "--archive-plan 输出可再生产物的精确路径 + 恢复方式（dry-run 计划，等待用户确认）。"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("projects_root", help="projects 根目录")
    parser.add_argument("--top", type=int, default=5, help="Top N 项目（默认 5）")
    parser.add_argument("--json-out", help="JSON 报告输出路径（默认 stdout）")
    parser.add_argument(
        "--archive-plan",
        metavar="OUT_JSON",
        help="输出可再生产物归档计划（精确路径/大小/恢复方式；dry-run，不执行）",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = Path(args.projects_root)
    if not root.is_dir():
        print(f"[ERROR] projects root not found: {root}", file=sys.stderr)
        return 2
    report = build_report(root, top=args.top)
    if args.archive_plan:
        plan: dict[str, Any] = {
            "schema": "ppt-master.space-archive-plan.v1",
            "projects_root": str(root),
            "note": "dry-run plan only — nothing is deleted. User approval required before any cleanup.",
            "projects": [
                {
                    "project": p.name,
                    "renewable_bytes": sum(item["bytes"] for item in _archive_plan(p)),
                    "items": _archive_plan(p),
                }
                for p in sorted(root.iterdir())
                if p.is_dir()
            ],
        }
        Path(args.archive_plan).write_text(
            json.dumps(plan, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        print(f"[PLAN] archive plan (dry-run) -> {args.archive_plan}")
    if args.json_out:
        Path(args.json_out).write_text(
            json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        print(f"[REPORT] {args.json_out}")
    else:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    s = report["summary"]
    print(f"\n[SUMMARY] {s['projects']} projects, {s['bytes'] / 1024**2:.1f} MiB total, "
          f"{s['renewable_bytes'] / 1024**2:.1f} MiB renewable (read-only report)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
